env:
  global:
    - NDK_VERSION=r10e

sudo: false

language:
  - android
jdk:
  - oraclejdk8

before_install:
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter platform-tools
  - echo y|android update sdk --all --no-ui --force --filter build-tools-23.0.2
  - echo y|android update sdk --all --no-ui --force --filter android-23
  - echo y|android update sdk --all --no-ui --force --filter extra-android-m2repository
  - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
  - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
  - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
  - ./gradlew build --info

after_failure:
  - cat build/outputs/lint-results.xml
